version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: "/"
    target-branch: v5.x.x
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: v5.x.x
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
